# Generated by Django 4.1.2 on 2022-10-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cat', 'Cat'), ('Fish', 'Fish'), ('None', 'None'), ('Exotic', 'Exotic'), ('Rabbit', 'Rabbit'), ('Parrot', 'Parrot'), ('Hamster', 'Hamster'), ('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('Other', 'Other')], default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=100, null=True)),
                ('breed', models.CharField(blank=True, default='Undefined', max_length=255, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_desc.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal_desc.animaltype'),
        ),
    ]
