# Generated by Django 4.1.2 on 2022-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0002_animal_avatar_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('None', 'None'), ('Guinea Pig', 'Guinea Pig'), ('Fish', 'Fish'), ('Parrot', 'Parrot'), ('Rabbit', 'Rabbit'), ('Exotic', 'Exotic'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Hamster', 'Hamster')], default='None', max_length=50),
        ),
    ]
