# Generated by Django 4.1.2 on 2022-10-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0003_animal_slug_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('None', 'None'), ('Female', 'Female')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Hamster', 'Hamster'), ('None', 'None'), ('Rabbit', 'Rabbit'), ('Parrot', 'Parrot'), ('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other'), ('Exotic', 'Exotic')], default='None', max_length=50),
        ),
    ]
