# Generated by Django 4.1.2 on 2022-10-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0005_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Female', 'Female'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('Parrot', 'Parrot'), ('None', 'None'), ('Other', 'Other'), ('Exotic', 'Exotic'), ('Rabbit', 'Rabbit'), ('Cat', 'Cat'), ('Hamster', 'Hamster')], default='None', max_length=50),
        ),
    ]
