# Generated by Django 4.1.2 on 2022-10-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0007_alter_animal_slug_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal_desc.animaltype'),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animal_desc.animal'),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Fish', 'Fish'), ('Hamster', 'Hamster'), ('Guinea Pig', 'Guinea Pig'), ('Exotic', 'Exotic'), ('None', 'None'), ('Other', 'Other'), ('Parrot', 'Parrot'), ('Dog', 'Dog'), ('Rabbit', 'Rabbit')], default='None', max_length=50),
        ),
    ]
