# Generated by Django 4.1.2 on 2022-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0008_alter_animal_type_alter_animalprofile_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('None', 'None'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Parrot', 'Parrot'), ('Hamster', 'Hamster'), ('Other', 'Other'), ('Dog', 'Dog'), ('Rabbit', 'Rabbit'), ('None', 'None'), ('Exotic', 'Exotic'), ('Guinea Pig', 'Guinea Pig'), ('Fish', 'Fish')], default='None', max_length=50),
        ),
    ]
