# Generated by Django 4.1.2 on 2022-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0009_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Guinea Pig', 'Guinea Pig'), ('Parrot', 'Parrot'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Dog', 'Dog'), ('Rabbit', 'Rabbit'), ('Hamster', 'Hamster'), ('None', 'None'), ('Exotic', 'Exotic'), ('Other', 'Other')], default='None', max_length=50),
        ),
    ]
