# Generated by Django 4.1.2 on 2022-10-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0010_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('None', 'None'), ('Female', 'Female')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Exotic', 'Exotic'), ('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('Parrot', 'Parrot'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Hamster', 'Hamster'), ('None', 'None'), ('Other', 'Other'), ('Cat', 'Cat')], default='None', max_length=50),
        ),
    ]
