# Generated by Django 4.1.2 on 2022-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0011_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='animals/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Exotic', 'Exotic'), ('Parrot', 'Parrot'), ('Dog', 'Dog'), ('Guinea Pig', 'Guinea Pig'), ('Rabbit', 'Rabbit'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Other', 'Other'), ('Hamster', 'Hamster'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
