# Generated by Django 4.1.2 on 2022-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0012_alter_animal_avatar_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Rabbit', 'Rabbit'), ('Guinea Pig', 'Guinea Pig'), ('Hamster', 'Hamster'), ('None', 'None'), ('Exotic', 'Exotic'), ('Dog', 'Dog'), ('Parrot', 'Parrot'), ('Cat', 'Cat'), ('Other', 'Other')], default='None', max_length=50),
        ),
    ]
