# Generated by Django 4.1.2 on 2022-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0014_alter_animal_avatar_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Guinea Pig', 'Guinea Pig'), ('None', 'None'), ('Parrot', 'Parrot'), ('Fish', 'Fish'), ('Cat', 'Cat'), ('Dog', 'Dog'), ('Hamster', 'Hamster'), ('Rabbit', 'Rabbit'), ('Other', 'Other'), ('Exotic', 'Exotic')], default='None', max_length=50),
        ),
    ]
