# Generated by Django 4.1.2 on 2022-10-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0015_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Parrot', 'Parrot'), ('Guinea Pig', 'Guinea Pig'), ('None', 'None'), ('Fish', 'Fish'), ('Rabbit', 'Rabbit'), ('Dog', 'Dog'), ('Other', 'Other'), ('Exotic', 'Exotic'), ('Hamster', 'Hamster')], default='None', max_length=50),
        ),
    ]
