# Generated by Django 4.1.2 on 2022-10-10 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0016_alter_animaltype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('None', 'None'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('None', 'None'), ('Fish', 'Fish'), ('Exotic', 'Exotic'), ('Other', 'Other'), ('Rabbit', 'Rabbit'), ('Hamster', 'Hamster'), ('Parrot', 'Parrot')], default='None', max_length=50),
        ),
    ]
