# Generated by Django 4.1.2 on 2022-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0017_animal_create_date_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='small_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Rabbit', 'Rabbit'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Hamster', 'Hamster'), ('Other', 'Other'), ('Guinea Pig', 'Guinea Pig'), ('None', 'None'), ('Exotic', 'Exotic'), ('Parrot', 'Parrot'), ('Fish', 'Fish')], default='None', max_length=50),
        ),
    ]
