# Generated by Django 4.1.2 on 2022-10-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0018_animal_is_active_animalprofile_small_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_desc.animal'),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Parrot', 'Parrot'), ('Other', 'Other'), ('Guinea Pig', 'Guinea Pig'), ('None', 'None'), ('Dog', 'Dog'), ('Fish', 'Fish'), ('Rabbit', 'Rabbit'), ('Exotic', 'Exotic'), ('Hamster', 'Hamster'), ('Cat', 'Cat')], default='None', max_length=50),
        ),
    ]
