# Generated by Django 4.1.2 on 2022-10-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0020_alter_animal_type_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal_desc.animaltype'),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Parrot', 'Parrot'), ('Hamster', 'Hamster'), ('None', 'None'), ('Other', 'Other'), ('Exotic', 'Exotic')], default='None', max_length=50),
        ),
    ]
