# Generated by Django 4.1.2 on 2022-10-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0023_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('None', 'None'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Dog', 'Dog'), ('Guinea Pig', 'Guinea Pig'), ('Rabbit', 'Rabbit'), ('Cat', 'Cat'), ('Parrot', 'Parrot'), ('None', 'None'), ('Fish', 'Fish'), ('Exotic', 'Exotic'), ('Hamster', 'Hamster')], default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='animals/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_desc.animal')),
            ],
        ),
    ]
