# Generated by Django 4.1.2 on 2022-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0024_alter_animal_age_alter_animal_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='where_to_get',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Female', 'Female'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Fish', 'Fish'), ('Exotic', 'Exotic'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit'), ('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('Hamster', 'Hamster'), ('Other', 'Other'), ('None', 'None'), ('Parrot', 'Parrot')], default='None', max_length=50),
        ),
    ]
