# Generated by Django 4.1.2 on 2022-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0025_animalprofile_where_to_get_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Rabbit', 'Rabbit'), ('Hamster', 'Hamster'), ('None', 'None'), ('Dog', 'Dog'), ('Other', 'Other'), ('Guinea Pig', 'Guinea Pig'), ('Parrot', 'Parrot'), ('Fish', 'Fish'), ('Exotic', 'Exotic')], default='None', max_length=50),
        ),
    ]
