# Generated by Django 4.1.2 on 2022-10-16 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal_desc', '0027_animal_created_by_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Rabbit', 'Rabbit'), ('Exotic', 'Exotic'), ('Cat', 'Cat'), ('Dog', 'Dog'), ('Parrot', 'Parrot'), ('Fish', 'Fish'), ('Other', 'Other'), ('Guinea Pig', 'Guinea Pig'), ('Hamster', 'Hamster'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
