# Generated by Django 4.1.2 on 2022-10-16 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal_desc', '0028_alter_animal_created_by_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('None', 'None'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Guinea Pig', 'Guinea Pig'), ('Exotic', 'Exotic'), ('Hamster', 'Hamster'), ('Cat', 'Cat'), ('Parrot', 'Parrot'), ('Dog', 'Dog'), ('None', 'None'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Other', 'Other')], default='None', max_length=50),
        ),
    ]
