# Generated by Django 4.1.2 on 2022-10-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0030_alter_animal_name_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animal_desc.animaltype'),
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Female', 'Female'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Rabbit', 'Rabbit'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Exotic', 'Exotic'), ('Guinea Pig', 'Guinea Pig'), ('Dog', 'Dog'), ('None', 'None'), ('Hamster', 'Hamster'), ('Parrot', 'Parrot'), ('Other', 'Other')], default='None', max_length=50),
        ),
    ]
