# Generated by Django 4.1.2 on 2022-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0031_alter_animal_type_alter_animalprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('None', 'None'), ('Female', 'Female')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Hamster', 'Hamster'), ('Exotic', 'Exotic'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Guinea Pig', 'Guinea Pig'), ('None', 'None'), ('Cat', 'Cat'), ('Dog', 'Dog'), ('Parrot', 'Parrot'), ('Other', 'Other')], default='None', max_length=50),
        ),
    ]
