# Generated by Django 4.1.2 on 2022-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0033_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Parrot', 'Parrot'), ('Hamster', 'Hamster'), ('Exotic', 'Exotic'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('None', 'None'), ('Guinea Pig', 'Guinea Pig'), ('Other', 'Other')], default='None', max_length=50),
        ),
    ]
