# Generated by Django 4.1.2 on 2022-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0034_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Exotic', 'Exotic'), ('Parrot', 'Parrot'), ('None', 'None'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Rabbit', 'Rabbit'), ('Guinea Pig', 'Guinea Pig'), ('Hamster', 'Hamster'), ('Dog', 'Dog')], default='None', max_length=50),
        ),
    ]
