# Generated by Django 4.1.2 on 2022-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0035_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Female', 'Female'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Hamster', 'Hamster'), ('Rabbit', 'Rabbit'), ('Parrot', 'Parrot'), ('Guinea Pig', 'Guinea Pig'), ('Fish', 'Fish'), ('Cat', 'Cat'), ('Exotic', 'Exotic'), ('Dog', 'Dog'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
