# Generated by Django 4.1.2 on 2022-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0037_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('None', 'None'), ('Male', 'Male')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Hamster', 'Hamster'), ('Guinea Pig', 'Guinea Pig'), ('Exotic', 'Exotic'), ('Other', 'Other'), ('Cat', 'Cat'), ('None', 'None'), ('Parrot', 'Parrot'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish')], default='None', max_length=50),
        ),
    ]
