# Generated by Django 4.1.2 on 2022-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_desc', '0039_alter_animalprofile_gender_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('Parrot', 'Parrot'), ('Fish', 'Fish'), ('Exotic', 'Exotic'), ('Guinea Pig', 'Guinea Pig'), ('None', 'None'), ('Other', 'Other'), ('Dog', 'Dog'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit'), ('Hamster', 'Hamster')], default='None', max_length=50),
        ),
    ]
