# Generated by Django 4.1.2 on 2022-10-05 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
